accounts/urls.py
from django.urls import path
from .views import signup_view, login_view, logout_view

urlpatterns = [
    path('signup', signup_view, name='signup'),
    path('login', login_view, name='login'),
    path('logout', logout_view, name='logout')
]

my_library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('products.urls')),
    path('', include('accounts.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.contrib import admin
from django.urls import path
from .views import index, show_author, show_product, add_new_comment, delete_comment,ver_carrito, special_author_page, special_price, product_views
from .views import add_carrito, actualizar_cantidad, eliminar_carrito, show_genero, show_filter, pay_shoppingCard,special_most_sale, busqueda

urlpatterns = [
    path('', index, name = 'index'),
    path('author/<int:id>', show_author, name='show_author'),
    path('product/<int:id>', show_product, name='show_product'),
    path('product/<int:id>/add_new_comment', add_new_comment, name='add_new_comment'),
    path('product/<int:id_comment>/<int:id_libro>/delete', delete_comment, name='delete_comment'),
    path('shopping_cart/<int:id>', add_carrito, name='add_carrito'),
    path('shopping_cart/', ver_carrito, name='ver_carrito'),
    path('shopping_cart/actualizar/<int:id>', actualizar_cantidad, name='actualizar_cantidad'),
    path('shopping_cart/eliminar/<int:id>', eliminar_carrito, name='eliminar_carrito'),
    path('showGenero/<str:Genero>', show_genero, name='show_genero'),
    path('showGenero/<str:Genero>/filter/<int:min>/<int:max>', show_filter, name='show_filter'),
    path('Checkout/pay_shopping', pay_shoppingCard, name='pay_shoppingCard'),
    path('special_most_sale/', special_most_sale, name='special_most_sale'),
    path('special_author_page/<str:author>', special_author_page, name='special_author_page'),
    path('special_price', special_price, name='special_price'),
    path('busqueda', busqueda, name='busqueda'),
    path('products/<str:Tipo>', product_views, name='product_views')
]

products/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

#terminar el modelo
class Libro(models.Model):
    
    name = models.CharField(max_length=100)
    
    author = models.ForeignKey(
        'products.Author',
        on_delete=models.CASCADE,
        related_name='products',
        null=True, blank=True
    )
    
    description = models.TextField(null=True, blank=True)
    
    genero = models.CharField(max_length=50)
    
    type = models.CharField(max_length=50, default='Libro')
    
    image = models.ImageField(blank=True, null=True, upload_to = 'media/products')
    
    price = models.DecimalField(decimal_places=2, max_digits=10, null=True)
    
    special_price = models.DecimalField(decimal_places=2, max_digits=10, null=True, blank=True)
    
    quantity = models.PositiveIntegerField(default=0)
    
    count_sale = models.PositiveIntegerField(default=0)
    
    created_date = models.DateTimeField(
        default=timezone.now)
    published_date = models.DateTimeField(
        blank=True, null=True)
    
    def __str__(self):
        return f'{self.name} | {self.author}'
    
    
class Author(models.Model):
    author =  models.CharField(max_length=200, null=True)
    
    description = models.TextField(null=True, blank=True)
    
    image = models.ImageField(blank=True, null=True, upload_to = 'media/author')
    
    created_date = models.DateTimeField(
        default=timezone.now)
    published_date = models.DateTimeField(
        blank=True, null=True)
    
    def __str__(self):
        return f'{self.author}'


class Comment(models.Model):
    
    product = models.ForeignKey(
        'products.Libro',
        on_delete = models.CASCADE,
        related_name = 'comments'
    )
    author = models.CharField(max_length=200)
    
    text = models.TextField()
    
    created_data = models.DateField(default=timezone.now)
    
    approved_comment = models.BooleanField(default=False)
    
    def approve(self):
        self.approved_comment = True
        self.save()
        
    def __str__(self):
        return self.text
    
class Carrito(models.Model):
    
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    producto = models.ForeignKey(Libro, on_delete=models.CASCADE, related_name="carrito")
    cantidad = models.PositiveIntegerField(default=1)
    
    def __str__(self):
        return f'{self.usuario} - {self.producto}'

products/forms.py
from .models import Comment
from django.forms import ModelForm, Textarea


class CommentsForm(ModelForm):
    
    class Meta:
        model = Comment
    
        fields = ('text',)
    
        widgets = {
            'text': Textarea(attrs={
                'class':'form-control',
                'arial-label':'Comentarios',
                'placeholder':'Deja tu comentario',
                'id':'formComment'
            })
            
    }

products/views.py
from django.shortcuts import get_object_or_404, render, redirect
from .models import Libro, Author, Comment, Carrito
from .forms import CommentsForm
from django.core.paginator import Paginator


def index(request):
    #logica
    #Aqui jugamos un poco con el filtro y con el order_by para que las consultas me traigan del modelo Libro todos las que son type Libro y ordenadas
    
    products = Libro.objects.filter(type='Libro').order_by('-id')[:8]

      
    return render( request,'products/list_of_products.html', {'products': products})


def special_most_sale(request):
    
    products = Libro.objects.order_by('-count_sale')[:24]
    
    paginator_products = Paginator(products,12)
    
    page_number = request.GET.get("page")
    
    page_obj_prod = paginator_products.get_page(page_number)
    
    return render(request, 'special/special.html', {'products' : page_obj_prod} )


def product_views(request, Tipo):
    
    products = Libro.objects.filter(genero=Tipo)
    
    paginator_products = Paginator(products,12)
    
    page_number = request.GET.get("page")
    
    page_obj_prod = paginator_products.get_page(page_number)
    
    return render(request, 'productStore/product.html', {'products' : page_obj_prod, 'tipo':Tipo})


def special_author_page(request, author):
    author = get_object_or_404(Author, author=author)
    
    product = Libro.objects.filter(author=author)
    
    
    paginator_products = Paginator(product,12)
    
    page_number =request.GET.get("page")
    
    page_obj_prod = paginator_products.get_page(page_number)
    
    return render(request, 'special/author_page.html', {'products': page_obj_prod})


def special_price(request):
    
    #Con este __isnull=False le estamos diciendo al filtro que me traiga los datos que en el apartado de special_price no sea nulo.
    product = Libro.objects.filter(special_price__isnull=False)
    
    paginator_products = Paginator(product, 12)
    
    page_number = request.GET.get("page")
    
    page_obj_prod = paginator_products.get_page(page_number)
    
    return render(request, 'special/special_price.html', {'products':page_obj_prod})


def show_genero(request, Genero):

    
    products = Libro.objects.filter(genero=Genero)
    #Concretamente tuve que utilizar author__in para poder filtrar los autores de los libros filtrados por genero
    authors = Author.objects.filter(author__in=products)
    
    #paginator
    
    paginator_products = Paginator(products, 12)
    
    paginator_authors = Paginator(authors, 12)
    
    page_number = request.GET.get("page")    
    
    page_obj_prod = paginator_products.get_page(page_number)
    
    page_obj_author = paginator_authors.get_page(page_number)
    

    return render( request,'generos/genero.html', {'genero':Genero,'products': page_obj_prod, 'authors': page_obj_author})

    
def show_filter (request, Genero, min, max):
    
    products = Libro.objects.filter(genero=Genero, price__gte=min, price__lte=max)
    #Concretamente tuve que utilizar author__in para poder filtrar los autores de los libros filtrados por genero
    authors = Author.objects.filter(author__in=products)
    
    #paginator
    
    paginator_products = Paginator(products, 12)
    
    paginator_authors = Paginator(authors, 12)
    
    page_number = request.GET.get("page")    
    
    page_obj_prod = paginator_products.get_page(page_number)
    
    page_obj_author = paginator_authors.get_page(page_number)
    
    
    return render( request,'generos/genero.html', {'genero':Genero,'products': page_obj_prod, 'authors': page_obj_author})
    
    

def show_author(request, id ):
    
    product = Libro.objects.get(id=id)
    
    return render(request, 'products/show_author.html', {'product':product})



def show_product(request, id):
    
    product = Libro.objects.get(id=id)
    
    comments = Comment.objects.filter(product=id)
    
    form = CommentsForm()
    
    return render(request, 'products/show_product.html',
                  {'product':product, 
                   'comments':comments, 
                   'form':form})
    
    
#Shopping Cart 

def add_carrito(request, id):
    libro = Libro.objects.get(id=id) 
    carrito, creado = Carrito.objects.get_or_create(usuario=request.user, producto=libro)
    if not creado:
        carrito.cantidad += 1
        carrito.save()
    return redirect('ver_carrito')
    
    
def ver_carrito(request):
    #Aqui instanciamos un objeto de Carrito donde traemos todos los objetos con el filtro de que sea el usuario logeado 
    carrito = Carrito.objects.filter(usuario=request.user)
    #Creamos esta variable para iniciar el bucle
    total = 0
    for item in carrito:
        if item.producto.special_price:
            suma = item.producto.special_price  * item.cantidad
        else:
            suma = item.producto.price  * item.cantidad
        total += suma

    
    return render(request, 'shopping/carritoC.html', {"carrito":carrito, "total":total})
    
    
def pay_shoppingCard(request):
    
    carritos = Carrito.objects.filter(usuario=request.user)
 
    
    
    for carrito in carritos:
        product = carrito.producto
        
        cantidadCarrito = carrito.cantidad
        cantidadProducto = product.quantity
        
        if cantidadProducto >= cantidadCarrito:
            product.quantity = cantidadProducto - cantidadCarrito
            product.count_sale += carrito.cantidad
            carrito.delete()
            product.save()
    
        else:
             return redirect('ver_carrito')
    return redirect('ver_carrito')


def actualizar_cantidad(request, id):
    
    libro = get_object_or_404(Carrito, id=id)
    
    if request.method == 'POST':
        
        new_quantity = request.POST.get('cantidad')
        libro.cantidad = new_quantity
        libro.save()
        
    return redirect('ver_carrito')


def eliminar_carrito(request, id):
    
    libro = get_object_or_404(Carrito, id=id)
    
    if request.method == 'POST':
        libro.delete()
    return redirect('ver_carrito')

    
    
    
    #Comentarios

#Crear comentarios
def add_new_comment(request, id):
    
    if request.method == 'POST':
    
        form = CommentsForm(request.POST)
        
        if form.is_valid:
            user = request.user
            product = Libro.objects.get(id=id)
            new_comment = form.save(commit=False)
            new_comment.author = user
            new_comment.product = product
            
            new_comment.save()
        return redirect('show_product',id)
    
    return redirect('show_product',id)





#Eliminar comentarios
def delete_comment(request, id_comment, id_libro):
    
    comment = Comment.objects.get(id=id_comment)
    comment.delete()
    return redirect('show_product',id_libro)
    


#Busqueda
def busqueda(request):
    
    #traemos todos los datos
    queryset = Libro.objects.all()
    
    #traemos el elemento input con el name busqueda
    query = request.GET.get('busqueda')
    
    #comprobamos si existe
    if query:
        #Aqui basicamente usanmos el filter para realizar un filtro el __icontains nos sirve para ver si existe dentro del name el query.
        #Hacemos dos filtro con el | para separarlos. Va a buscar en name y description
        queryset =queryset.filter(description__icontains=query) | queryset.filter(name__icontains=query)
        
    paginator_products = Paginator(queryset,12)
    
    page_number = request.GET.get("page")
    
    page_obj_prod = paginator_products.get_page(page_number)
    
        
    return render(request, 'busqueda/filter_search.html', {'query': query, 'queryset':page_obj_prod})
    

templates/products/list_of_products.html
{% extends 'base/base.html' %}

{% block content %}

<div class="">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-8">
                <div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
                    <div class="carousel-inner">
                        <div class="carousel-item">
                            <img class="img-fluid rounded"
                                src="https://www.libreriainternacional.com/media/Home/9788123777924_BANNER_WEB_3.png"
                                alt="Carousel 1">
                        </div>
                        <div class="carousel-item">
                            <img class="img-fluid rounded"
                                src="https://www.libreriainternacional.com/media/Home/Banner-web-Value-packs-Stefan-Zweig_1.png"
                                alt="Carousel 2">
                        </div>
                        <div class="carousel-item active">
                            <img class="img-fluid rounded"
                                src="https://www.libreriainternacional.com/media/Home/9786073911290-Banner-web-En-Agosto-nos-vemos-lanzamiento_1_.jpg"
                                alt="Carousel 3">
                        </div>
                    </div>
                    <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel"
                        data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Previous</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#myCarousel"
                        data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Next</span>
                    </button>
                </div>
            </div>
            <div class="col-md-4">
                <div class="row">
                    <div class="col-lg-12 mb-3">
                        <a href="{% url 'special_author_page' author='Arthur Conan Doyle' %}"> <img class="img-fluid rounded"
                                src="https://www.libreriainternacional.com/media/Home/Banner-web-391x144-px-Autor-del-mes-mayo.png"
                                alt="Banner 1"></a>
                    </div>
                    <div class="col-lg-12 mb-3">
                        <a href="{% url 'special_price' %}"> <img class="img-fluid rounded"
                                src="https://www.libreriainternacional.com/media/Home/Banner-web-Precios-especiales.jpg"
                                alt="Banner 2"></a>
                    </div>
                    <div class="col-lg-12">
                        <a href="{% url 'special_most_sale' %}">
                            <img class="img-fluid rounded"
                                src="https://www.libreriainternacional.com/media/Home/Banner-web-los-ma_s-vendidos-BESTSELLERS-391x144.png"
                                alt="Banner 3"></a>
                    </div>
                </div>
            </div>
        </div>
    </div>





    <h1 class="mt-5">Lo más reciente</h1>
    <div class="row row-cols-1 row-cols-md-4 g-4">
        {% for product in products %}
        <div class="col-md-3">
            <div class="card shadow-lg mb-4 bg-white rounded h-100">
                <a href={% url 'show_product' id=product.id %} class='text-decoration-none image-container'>
                    <img src="{{ product.image.url }}" class="card-img-top img-fluid " alt="{{ product.name }}"
                        style="height: 300px; object-fit: contain;">
                </a>
                <div class="card-body d-flex flex-column">
                    <h5 class="card-title text-center">{{ product.name|truncatechars:20}}</h5>
                    <strong class="text-center">{{ product.price }} USD</strong>
                    {% if product.special_price != false %}
                    <strong class="text-center">Socio Club: {{ product.special_price }} USD</strong>
                    {% endif %}
                    {% if product.quantity > 0 %}
                    <form action="{% url 'add_carrito' id=product.id %}" class="post-form mt-auto">
                        <button class="btn btn-darkred mt-auto" type='submit'>Agregar al Carrito</button>
                    </form>
                    {% else %}
                    <form action="" class="post-form mt-auto">
                        <button class="btn btn-darkred mt-auto " disabled type='submit'>Agotado</button>
                    </form>
                    {% endif %}
                </div>
            </div>

            
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

templates/products/show_author.html
{% extends 'base/base.html' %}

{% block content %}


<div class="row product-detail-row mt-4 mb-5">
    <div class="col-5">
        <img src="{{ product.author.image.url }}" class="card-img-top float-start rounded" alt="">
    </div>
    <div class="col-7">
        <div class="jumbotron">
            <h1 class="display-4">{{ product.author.author}}</h1>
            <hr class="my-4">
            <p>
                {{ product.author.description }}
            </p>
        </div>
    </div>
</div>



{% endblock %}

templates/products/show_product.html
{% extends 'base/base.html' %}

{% block content %}


<div class="row product-detail-row mt-4 mb-5">
    <div class="col-5">
        <img src="{{ product.image.url }}" class="card-img-top float-start rounded" alt="">
    </div>
    <div class="col-7">
        <div class="jumbotron">
            <h1 class="display-4">{{ product.name}}</h1>
            <a href="{% url 'show_author' id=product.id %}"
                class="text-dark d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start text-decoration-none "
                tabindex="-1" aria-disabled="true">
                <img src="{{ product.author.image.url }}" alt="mdo" width="32" height="32" class="rounded-circle">
                <div class="main-person-texts ">
                    <div class="main-person-title">{{ product.author }}</div>
                </div>
            </a>
            <hr class="my-4">
            <p>
                {{ product.description }}
            </p>
            <h5 style="color : rgb(139,0,0); font-weight: bold;"> ${{ product.price }}</h5>
            <br>
            {% if product.special_price != false %}
                    <strong class="text-center">Socio Club: {{ product.special_price }} USD</strong>
            {% endif %}
        </div>
        <div class="">
            {% if product.quantity > 0 %}
            <form action="{% url 'add_carrito' id=product.id %}" class="post-form mt-auto">
                <button class="btn btn-darkred mt-auto" type='submit'>Agregar al Carrito</button>
            </form>
            {% else %}
            <form action="" class="post-form mt-auto">
                 <button class="btn btn-darkred mt-auto " disabled type='submit'>Agotado</button>
            </form>
            {% endif %}
        </div>
    </div>
</div>





{% if user.perms.products.view_comment %}{% endif %}
<div class="row d-flex">
    <div class="col-md-5 comment-column">
        <form action="{% url 'add_new_comment' id=product.id %}" class="post-form" method="post">
            {% csrf_token %}
            <div class="input-group mb-4">
                {{ form.text }}
            </div>
            <button type="submit" class="btn btn-darkred">Enviar</button>
        </form>
    </div>
    
    <div class="col-md-7">
        <h2 class="comment-title text-left">Comentarios</h2>
        {% for comment in comments %}
        <div class="comment mb-4 p-3 border rounded">
            <div class="d-flex justify-content-between">
                <div>
                    <div class="date text-muted">{{ comment.created_date }}</div>
                    <strong>{{ comment.author }}</strong>
                </div>
                {% if comment.author == request.user.username %}
                <div class="btn-group">
                    <button type="button" class="btn btn-link dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false"></button>
                    <ul class="dropdown-menu dropdown-menu-end">
                        <li>
                            <form action="{% url 'delete_comment' id_comment=comment.id id_libro=product.id %}" method="post">
                                {% csrf_token %}
                                <button type="submit" class="dropdown-item text-danger">Eliminar</button>
                            </form>
                        </li>
                    </ul>
                </div>
                {% endif %}
            </div>
            <p>{{ comment.text }}</p>
        </div>
        {% endfor %}
    </div>
</div>







{% endblock %}